services:
  mongo:
    image: mongo:latest
    container_name: camyou-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - camyou-net

  backend:
    build: .
    container_name: camyou-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=http://mongo:27017/camyou
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
    networks:
      - camyou-net

networks:
  camyou-net:
    driver: bridge

volumes:
  mongo-data:
